### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by Nomad1414** [sharkusmanch/playnite-ludusavi-restic#23]
Hello, thank you for the great project.

suggestion 
custome tag after game-stopped, a popup screen saying "enter tag for the game save".
an option to disable automatic backup

**Comment by sharkusmanch** [comment]
Hey, sure. Will look at getting those added:

- Option to disable automatic backup at game stopped event
- Option to prompt the user for a tag when game stopped event occurs

**Comment by sharkusmanch** [comment]
Added in v0.5.0

**Comment by Nomad1414** [comment]
thank you so much
