### ISSUE TITLE
Only backing up files in one location

### ISSUE THREAD

**Issue by Driek123** [sharkusmanch/playnite-ludusavi-restic#32]
Hello, thanks for creating this wonderful plugin. 

I'm currently playing through Assassin's Creed Syndicate, and the backup is currently only backing up the configuration file which is in a separate folder from the saves folder. 

Config location: <winDocuments>/Assassin's Creed Syndicate/AC.ini 
Saves: <root>/savegames/<storeUserId>/1875 

When I try to back up via ludusavi alone, it does back up files from both locations and therefore the saves are included. I copied the above locations from the manifest.yaml that comes with ludusavi, it's definitely picking them up. So it seems like this plugin is only able to support one path of saves at once at the moment. There's no error messages to share, I just restored the snapshots afterwards and realised only AC.ini is included. 

I can always manually run restic to backup properly with a post-game script, but that makes this plugin kinda redundant & I can't capture the in-game snapshots. If there is a way to manually specify the correct saves pathway, or to specify multiple pathways, it would be great. 

Hope that makes sense, thank you very much.

**Comment by sharkusmanch** [comment]
Thanks for reporting. I personally have a few games that have multiple paths backed up, so I think there's something else at play here.

Can you share the following?

```
 ludusavi backup --preview --api "Assassin's Creed Syndicate"
```

restic snapshot paths
```
restic snapshots YOUR_SNAPSHOT_ID
```

I'll try to reproduce on my end in the meantime

**Comment by sharkusmanch** [comment]
Just reinstalled AC Syndicate on my machine and was able to do the backup as expected:

```
PS C:\Users\marcus> restic snapshots -r rclone:restic:/gamesaves f3845da0
repository c495813c opened successfully, password is correct
ID        Time                 Host            Tags                        Paths
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
f3845da0  2022-04-01 10:09:38  GAMING-DESKTOP  Assassin's Creed Syndicate  C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\REDACTED\1875\1.save
                                                                           C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\REDACTED\1875\2.save
                                                                           C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\REDACTED\1875\3.save
                                                                           C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\REDACTED\1875\4.save
                                                                           C:\Users\marcus\Documents\Assassin's Creed Syndicate\AC.ini
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 snapshots
```

> I don't know if I fully understand what you're asking for regarding the second command

Trying to see the list of files contained in your restic backup. Can you run the same command I ran above, just changing your snapshot id and repository as needed?

**Comment by Driek123** [comment]
Oh I see. Below is my output. It really only has that one file somehow, not sure why now. 

```
PS C:\Users\USERNAME> restic snapshots -r "<local path>\saves" c1cae5df
repository 2911a89e opened successfully, password is correct
ID        Time                 Host        Tags                                 Paths
---------------------------------------------------------------------------------------------------------------------------------------
c1cae5df  2022-04-01 19:03:04  pcname      Assassin's Creed Syndicate,gameplay  C:\Users\USERNAME\Documents\Assassin's Creed Syndicate\AC.ini
---------------------------------------------------------------------------------------------------------------------------------------
1 snapshots
```

**Comment by sharkusmanch** [comment]
Hmm.. this is really strange.

I'll keep looking into it, in the meantime can you share the following?

- Ludusavi version
- Restic version
- Do you have any other Ubisoft Connect games you can test with? Curious if it's a broader issue with the Ubisoft save paths or something

**Comment by sharkusmanch** [comment]
Also, do you have a "root" defined in Ludusavi for Ubisoft?

Here's mine for example:
<img width="871" alt="Screen Shot 2022-04-01 at 6 39 33 PM" src="https://user-images.githubusercontent.com/9328629/161360636-cc664acc-f4c9-40e6-a129-b557c5aefc3b.png">

**Comment by Driek123** [comment]
I think I fixed it? By adding another root to where I actually installed the game. My game was installed outside of the default installation location specified in uplay. 

Originally my roots looked like this (so yes there was uplay included): 
![original](https://user-images.githubusercontent.com/16720778/161368635-8f6b3204-80c3-4b92-ab6c-2a9016757e72.png)

I added the install location for the game on another drive (G:\Downloads\Ubisoft): 
![ubi only](https://user-images.githubusercontent.com/16720778/161368646-2ba0be6f-b4a2-4641-bc43-697ad9192f9e.png)

Now when I do a new snapshot and check the files in I get all the intended files!: 
```
PS C:\Users\REDACTED> restic snapshots -r "<local path>\restic saves" ffd65692
repository 2911a89e opened successfully, password is correct
ID        Time                 Host        Tags                               Paths
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ffd65692  2022-04-02 16:41:30  pcname      Assassin's Creed Syndicate,manual  C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\REDACTED\1875\1.save
                                                                              C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\REDACTED\1875\2.save
                                                                              C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\REDACTED\1875\3.save
                                                                              C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\REDACTED\1875\4.save
                                                                              C:\Users\REDACTED\Documents\Assassin's Creed Syndicate\AC.ini
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 snapshots
```

As an extra I decided to try going into uplay's settings and changing my default installation location to the folder where the game is currently installed: 
![uplay settings](https://user-images.githubusercontent.com/16720778/161369301-67db8646-4d0b-4ca1-b1ca-34f99a0ab682.png)

Then took out the extra root location so ludusavi only has the ubi launcher folder listed:  
![ubi mainfolder only](https://user-images.githubusercontent.com/16720778/161368925-31043bbc-eff0-45a7-89ff-f1c3c49b6208.png)

Did another snapshot and still got all the files like above. The strange thing though is that when I changed everything in uplay & ludusavi back to as it was before, doing another snapshot still captures all 5 intended files now. So I'm not sure exactly what happened here, and I can't seem to replicate the bug again despite having the same settings :( weird 

If you still want the other specs: 
- Ludusavi version: 0.10.0
- Restic version: 0.13.0
- I don't have any other ubisoft games to test with unfortunately, but seeing as the problem resolved itself by playing with ubisoft's folders it might just be a quirk with ubisoft games as a whole since they all use the same paths as far as I'm aware.

**Comment by sharkusmanch** [comment]
Cool sounds like it was a ludusavi root issue, since it's working for you now.

I'll add a troubleshooting doc to the repo that goes over situations like this, since there are a lot of moving parts.
