### ISSUE TITLE
Not backing up game data

### ISSUE THREAD

**Issue by greenconda** [sharkusmanch/playnite-ludusavi-restic#42]
Not backing up game data for games installed from xbox game pass, even though ludasavi ui detects the game and the save files and backup and restores just fine.
Game used: Prey(2017)

Error Message : No save files found for "GAME NAME"

Happens both the times when auto backup is enabled or when trying to backup from main menu (right click options)

**Comment by sharkusmanch** [comment]
Sounds like a game title mismatch between the game in Playnite vs PCGamingWiki / ludusavi manifest.

Can you confirm the game name in Playnite is exactly "Prey (2017)"?

**Comment by greenconda** [comment]
Yes, it was just Prey, I manually edited it to Prey (2017) and it works. Is it possible for extension to take name from ludusavi itself and not playnite ?

**Comment by sharkusmanch** [comment]
Unfortunately, it's not feasible.

That would require ludusavi to scan the filesystem every time and then have the extension pick a best match out of the results.

I recommend using the PCGamingWiki metadata extension to manage the `Name` metadata on your library. This will help ensure game names match PCGamingWiki where ludusavi creates its manifest from.
